<?php

    //-------------------- add feature img

    add_theme_support( 'post-thumbnails' );

    add_filter( 'post_thumbnail_html', 'remove_thumbnail_dimensions', 10 );
    add_filter( 'image_send_to_editor', 'remove_thumbnail_dimensions', 10 );

    function remove_thumbnail_dimensions( $html ) {
        $html = preg_replace( '/(width|height)=\"\d*\"\s/', "", $html );
        return $html;
    }


    //-------------------- add custom menu support

    add_theme_support( 'menus' );

    function fot_menus() {
        $locations = array(
            'headermenu' => 'Header menu',
            'footermenu' => 'Footer menu',
        );
        register_nav_menus( $locations );

    }
    add_action( 'init', 'fot_menus' );

    // Register Custom Taxonomy
    function cork_color() {

	    $labels = array(
		    'name'                       => 'Korkfarger',
		    'singular_name'              => 'Korkfarge',
		    'menu_name'                  => 'Korkfarger',
		    'all_items'                  => 'All Items',
		    'parent_item'                => 'Parent Item',
		    'parent_item_colon'          => 'Parent Item:',
		    'new_item_name'              => 'New Item Name',
		    'add_new_item'               => 'Add New Item',
		    'edit_item'                  => 'Edit Item',
		    'update_item'                => 'Update Item',
		    'view_item'                  => 'View Item',
		    'separate_items_with_commas' => 'Separate items with commas',
		    'add_or_remove_items'        => 'Add or remove items',
		    'choose_from_most_used'      => 'Choose from the most used',
		    'popular_items'              => 'Popular Items',
		    'search_items'               => 'Search Items',
		    'not_found'                  => 'Not Found',
		    'no_terms'                   => 'No items',
		    'items_list'                 => 'Items list',
		    'items_list_navigation'      => 'Items list navigation',
	    );
	    $args = array(
		    'labels'                     => $labels,
		    'hierarchical'               => false,
		    'public'                     => true,
		    'show_ui'                    => true,
		    'show_admin_column'          => true,
		    'show_in_nav_menus'          => true,
		    'show_tagcloud'              => true,
	    );
	    register_taxonomy( 'cork_color', array( 'post' ), $args );

    }
    add_action( 'init', 'cork_color', 0 );

    // Register Custom Taxonomy
    function beer_type() {

	    $labels = array(
		    'name'                       => 'Øltyper',
		    'singular_name'              => 'Øltype',
		    'menu_name'                  => 'Øltyper',
		    'all_items'                  => 'All Items',
		    'parent_item'                => 'Parent Item',
		    'parent_item_colon'          => 'Parent Item:',
		    'new_item_name'              => 'New Item Name',
		    'add_new_item'               => 'Add New Item',
		    'edit_item'                  => 'Edit Item',
		    'update_item'                => 'Update Item',
		    'view_item'                  => 'View Item',
		    'separate_items_with_commas' => 'Separate items with commas',
		    'add_or_remove_items'        => 'Add or remove items',
		    'choose_from_most_used'      => 'Choose from the most used',
		    'popular_items'              => 'Popular Items',
		    'search_items'               => 'Search Items',
		    'not_found'                  => 'Not Found',
		    'no_terms'                   => 'No items',
		    'items_list'                 => 'Items list',
		    'items_list_navigation'      => 'Items list navigation',
	    );
	    $args = array(
		    'labels'                     => $labels,
		    'hierarchical'               => false,
		    'public'                     => true,
		    'show_ui'                    => true,
		    'show_admin_column'          => true,
		    'show_in_nav_menus'          => true,
		    'show_tagcloud'              => true,
	    );
	    register_taxonomy( 'beer_type', array( 'post' ), $args );

    }
    add_action( 'init', 'beer_type', 0 );

    // ølstyrke
    /**
     * Generated by the WordPress Meta Box generator
     * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
     */

    function beer_strength_get_meta( $value ) {
	    global $post;

	    $field = get_post_meta( $post->ID, $value, true );
	    if ( ! empty( $field ) ) {
		    return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	    }
        else {
		    return false;
	    }
    }

    function beer_strength_add_meta_box() {
	    add_meta_box(
		    'beer_strength',
		    __( 'Ølstyrke', 'beer_strength' ),
		    'beer_strength_html',
		    'post',
		    'normal',
		    'default'
	    );
    }
    add_action( 'add_meta_boxes', 'beer_strength_add_meta_box' );

    function beer_strength_html( $post) {
	    wp_nonce_field( '_beer_strength_nonce', 'beer_strength_nonce' ); ?>

	    <p>Skriv inn ølstyrke</p>

	    <p>
		    <label for="beer_strength"><?php _e( 'Ølstyrke', 'beer_strength' ); ?></label><br>
		    <input style="width: 50%" type="text" name="beer_strength" id="beer_strength" value="<?php echo beer_strength_get_meta( 'beer_strength' ); ?>">
	    </p><?php
    }

    function beer_strength_save( $post_id ) {
	    if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	    if ( ! isset( $_POST['beer_strength_nonce'] ) || ! wp_verify_nonce( $_POST['beer_strength_nonce'], '_beer_strength_nonce' ) ) return;
	    if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	    if ( isset( $_POST['beer_strength'] ) ) {
		    update_post_meta( $post_id, 'beer_strength', esc_attr( $_POST['beer_strength'] ) );
        }
    }
    add_action( 'save_post', 'beer_strength_save' );

    /*
	    Usage: beer_strength_get_meta( 'beer_strength' )
    */

    /* TinyMCE editor */
    function bbp_enable_visual_editor( $args = array() ) {
      $args['tinymce'] = true;
      return $args;
    }
    add_filter( 'bbp_after_get_the_content_parse_args', 'bbp_enable_visual_editor' );


?>
